#Requires -Version 5.1
<#
.SYNOPSIS
  确保本机有 opencv.full Windows 预编译包（首次自动镜像下载，已有则跳过）。
  供 dartcv4 / opencv_dart 使用（含 videoio + ffmpeg）。

.PARAMETER Force
  强制重新下载并覆盖。
#>
param(
  [switch]$Force
)

$ErrorActionPreference = 'Stop'
$Root = Resolve-Path (Join-Path $PSScriptRoot '..')
$Dest = Join-Path $Root 'tools\opencv-full'
$Tar = Join-Path $Dest 'libopencv-windows-x64.tar.gz'
$Extract = Join-Path $Dest 'extract'
$EnvPs1 = Join-Path $Dest 'env.ps1'
$OpenCvVer = '4.12.0.0'
$Orig = "https://github.com/rainyl/opencv.full/releases/download/$OpenCvVer/libopencv-windows-x64.tar.gz"
$Mirrors = @(
  "https://ghfast.top/$Orig",
  "https://ghproxy.net/$Orig",
  "https://gh-proxy.com/$Orig",
  "https://mirror.ghproxy.com/$Orig",
  $Orig
)

function Find-OpenCvConfig([string]$root) {
  # VS2022/2026 生成器常识别不到 vc17；直接指向 staticlib 最稳。
  $static = Join-Path $root 'x64\vc17\staticlib\OpenCVConfig.cmake'
  if (Test-Path $static) { return (Join-Path $root 'x64\vc17\staticlib') }
  $direct = Join-Path $root 'OpenCVConfig.cmake'
  if (Test-Path $direct) { return $root }
  $hit = Get-ChildItem $root -Recurse -Filter 'OpenCVConfig.cmake' -ErrorAction SilentlyContinue |
    Where-Object { $_.DirectoryName -match 'staticlib$' } |
    Select-Object -First 1
  if ($hit) { return $hit.Directory.FullName }
  $hit2 = Get-ChildItem $root -Recurse -Filter 'OpenCVConfig.cmake' -ErrorAction SilentlyContinue |
    Select-Object -First 1
  if ($hit2) { return $hit2.Directory.FullName }
  return $null
}

function Write-EnvFile([string]$openCvDir) {
  $ffmpegDir = Join-Path $Extract 'ffmpeg\cmake'
  $cacheDir = Join-Path $Dest 'cache'
  @(
    '# Auto-generated by scripts/fetch_opencv_full.ps1'
    "`$env:DARTCV_DISABLE_DOWNLOAD_OPENCV = 'ON'"
    "`$env:OpenCV_DIR = '$openCvDir'"
    "`$env:FFMPEG_DIR = '$ffmpegDir'"
    "`$env:DARTCV_CACHE_DIR = '$cacheDir'"
  ) | Set-Content -Path $EnvPs1 -Encoding UTF8
}

$existing = if (Test-Path $Extract) { Find-OpenCvConfig $Extract } else { $null }
if (-not $Force -and $existing) {
  Write-EnvFile $existing
  Write-Host "OpenCV already present: $existing" -ForegroundColor Green
  Write-Host "OpenCV_DIR=$existing"
  Write-Host "Source env: . '$EnvPs1'"
  exit 0
}

if (-not (Get-Command curl.exe -ErrorAction SilentlyContinue)) {
  throw 'curl.exe not found (needed to download OpenCV). Install curl or use Windows 10+.'
}

New-Item -ItemType Directory -Force -Path $Dest | Out-Null
Remove-Item $Tar -Force -ErrorAction SilentlyContinue

Write-Host 'OpenCV local bundle missing — downloading via mirrors...' -ForegroundColor Cyan
$ok = $false
foreach ($u in $Mirrors) {
  Write-Host "TRY $u"
  & curl.exe -L --fail --retry 2 --connect-timeout 20 --max-time 600 -o $Tar $u
  if ($LASTEXITCODE -eq 0 -and (Test-Path $Tar) -and ((Get-Item $Tar).Length -gt 50MB)) {
    Write-Host ("OK size=" + (Get-Item $Tar).Length) -ForegroundColor Green
    $ok = $true
    break
  }
  Write-Host "FAIL exit=$LASTEXITCODE"
  Remove-Item $Tar -Force -ErrorAction SilentlyContinue
}
if (-not $ok) {
  throw 'All OpenCV mirrors failed. Check network, then re-run scripts/fetch_opencv_full.ps1'
}

if (Test-Path $Extract) { Remove-Item $Extract -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Extract | Out-Null

Write-Host 'Extracting...' -ForegroundColor Cyan
tar -xf $Tar -C $Extract
$openCvDir = Find-OpenCvConfig $Extract
if (-not $openCvDir) { throw "missing OpenCVConfig.cmake after extract under $Extract" }

$ffmpegCmake = Join-Path $openCvDir 'ffmpeg\cmake'
if (-not (Test-Path $ffmpegCmake)) {
  Write-Host "WARN: ffmpeg cmake not found at $ffmpegCmake (videoio may fail)" -ForegroundColor Yellow
}

Write-EnvFile $openCvDir

Write-Host ""
Write-Host "Ready: $openCvDir" -ForegroundColor Green
Write-Host "Before flutter build/run:"
Write-Host "  . '$EnvPs1'"
Write-Host "Or pack_windows.ps1 will source it automatically."
